### ISSUE TITLE
Upgrade to RabbitMQ Client 3.5

### ISSUE THREAD

**Issue by nabheet** [haf/log4net.RabbitMQ#16]
Do you have any plans to upgrade to RabbitMQ client 3.5?

https://groups.google.com/forum/#!topic/easynetq/Z6Z5tt-OCbk

We are getting this error:

log4net:ERROR Could not create Appender [AmqpAppender] of type [log4net.RabbitMQ.RabbitMQAppender, log4net.RabbitMQ]. Reported error follows.
System.TypeLoadException: Could not load type 'RabbitMQ.Client.Events.ConnectionShutdownEventHandler' from assembly 'RabbitMQ.Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce'.
   at log4net.RabbitMQ.RabbitMQAppenderBase.StartConnection()
   at log4net.RabbitMQ.RabbitMQAppenderBase.ActivateOptions()
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
log4net:ERROR Appender named [AmqpAppender] not found.
log4net: Hierarchy Threshold []

**Comment by haf** [comment]
PRs accepted.
