### ISSUE TITLE
Example config.xml contains invalid element : extendedProperties?

### ISSUE THREAD

**Issue by StefH** [haf/log4net.RabbitMQ#18]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [extendedProperties] to set object on [log4net.RabbitMQ.MessageProperties]

```xml
<extendedProperties value="true" />
```
Should it be?

```xml
<ExtendedData  value="true" />
```

**Comment by haf** [comment]
Probably

**Comment by haf** [comment]
Send PR?

**Comment by StefH** [comment]
I'll create a pull request for this.
