### ISSUE TITLE
How to handle logging when RabbitMQ is down or not available?

### ISSUE THREAD

**Issue by StefH** [haf/log4net.RabbitMQ#21]
When RabbitMQ is down or not available, this Library blocks on the StartConnection call. This means that every call to the log4netlogging will block until the connection timeout occurs.

Is it possible and a common design to make the logging call async? A possible solution would be to accept the loggingentry, add it to a fixedsize queue and then return immediately.

A second thread/task checks this internal queue and will start a connection and send messages.

Please advice.

**Comment by haf** [comment]
Like I write in the README, I would recommend moving to Logary -- and porting this (and NLog.RabbitMQ's) code to a target. If you do that, it's all async and all targets are started on a different thread, so your problem is solved by the fundamental software architecture.

**Comment by haf** [comment]
PS; there's a log4net adapter available, so you don't have to change all your code at the very start.
